FROM nvidia/cuda:10.2-base
CMD nvidia-smi

RUN apt-get update
RUN apt-get install git
RUN apt-get install build-essential checkinstall
RUN apt-get install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
RUN apt-get install ffmpeg libsm6 libxext6  -y
RUN apt-get install software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install python3.9 python3.9-dev python3.9-venv
RUN python3.9 -m ensurepip --default-pip --user

RUN cd /code/neuro-decode/
RUN python3.9 -m pip install -r requirements2.txt

RUN cd /code/taming-transformers/
RUN python3.9 -m pip install -e .

RUN cd /code/stable-diffusion/
RUN python3.9 -m pip install -e .

RUN apt-get install python3.10 python3.10-dev python3.10-venv